title: Emilio Nicolas Mardones
<a href="http://linkedin.com"><img src="https://www.citypng.com/public/uploads/preview/hd-linkedin-in-blue-balloon-icon-symbol-png-701751695045736e7luz21g4h.png" /></a>
description: Cybersecurity Student Portfolio | Pursuing recognized CompTIA CySA+ and Cisco CCST certifications
show_downloads: false
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
gem "github-pages", group: :jekyll_plugins
