title: Emilio Nicolas Mardones
description: Cybersecurity Student Portfolio | Pursuing recognized CompTIA CySA+ and Cisco CCST certifications
![vibrent_16](https://github.com/user-attachments/assets/6f97b23f-b5b3-41e6-b4d7-1da65b7c9dfb)
show_downloads: true
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
gem "github-pages", group: :jekyll_plugins
