title: Emilio Mardones
description: Cybersecurity & Network Technician Portfolio | Pursuing recognized CompTIA CySA+ and Cisco CCST certifications
show_downloads: false
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
gem "github-pages", group: :jekyll_plugins
