title: Emilio Nicolas Mardones
<a href="http://linkedin.com"><img src="http://img.shields.io/badge/-LinkedIn-0072b1?&style=for-the-badge&logo=linkedin&logoColor=white" /></a>
description: Cybersecurity Student Portfolio | Pursuing recognized CompTIA CySA+ and Cisco CCST certifications
show_downloads: false
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
gem "github-pages", group: :jekyll_plugins
