title: Emilio Mardones
# Auckland, New Zealand
#logo: 
#description: Future Cyber Security professional | Pursuing recognised CompTIA CySA+ & Cisco CCST Certifications
#show_downloads: true
theme: minima
